import type { BackofficeProduct } from './types';

export const MOCK_PRODUCTS: BackofficeProduct[] = [
  { id: 'p1', name: 'Camiseta Algodón Premium', sku: 'CAM-001', description: 'Camiseta de algodón 100% orgánico, corte relajado.', price: 29.99, originalPrice: null, currency: 'USD', stock: 45, category: 'Camisetas', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=CAM-001'], brand: 'CottonShop', sizes: ['S', 'M', 'L', 'XL'], colors: ['Blanco', 'Negro'] },
  { id: 'p2', name: 'Pantalón Chino Slim Fit', sku: 'PAN-002', description: 'Pantalón chino de corte slim con acabado lavado suave.', price: 59.99, originalPrice: null, currency: 'USD', stock: 3, category: 'Pantalones', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=PAN-002'], brand: 'CottonShop', sizes: ['30', '32', '34', '36'], colors: ['Beige', 'Negro', 'Azul'] },
  { id: 'p3', name: 'Chaqueta Vaquera Clásica', sku: 'CHQ-003', description: 'Chaqueta vaquera con corte clásico y botones metálicos.', price: 89.99, originalPrice: null, currency: 'USD', stock: 12, category: 'Chaquetas', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=CHQ-003'], brand: 'DenimCo', sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Azul', 'Negro'] },
  { id: 'p4', name: 'Vestido Floral Verano', sku: 'VES-004', description: 'Vestido ligero con estampado floral.', price: 49.99, originalPrice: null, currency: 'USD', stock: 20, category: 'Vestidos', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=VES-004'], brand: 'FloraMode', sizes: ['XS', 'S', 'M', 'L'], colors: ['Rosa', 'Azul'] },
  { id: 'p5', name: 'Sudadera Oversize', sku: 'SUD-005', description: 'Sudadera de algodón con corte oversized y capucha.', price: 44.99, originalPrice: 59.99, currency: 'USD', stock: 2, category: 'Sudaderas', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=SUD-005'], brand: 'UrbanStyle', sizes: ['M', 'L', 'XL'], colors: ['Gris', 'Negro'] },
  { id: 'p6', name: 'Short Deportivo', sku: 'SHR-006', description: 'Short deportivo con tecnología de secado rápido.', price: 24.99, originalPrice: null, currency: 'USD', stock: 30, category: 'Shorts', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=SHR-006'], brand: 'SportFit', sizes: ['S', 'M', 'L', 'XL'], colors: ['Negro', 'Gris'] },
  { id: 'p7', name: 'Camiseta Estampada Edición Limitada', sku: 'CAM-007', description: 'Camiseta con estampado exclusivo edición limitada.', price: 34.99, originalPrice: null, currency: 'USD', stock: 0, category: 'Camisetas', status: 'draft', images: ['https://placehold.co/200x200/E2E8F0/475569?text=CAM-007'], brand: 'UrbanStyle', sizes: ['S', 'M', 'L'], colors: ['Blanco'] },
  { id: 'p8', name: 'Cinturón Cuero Premium', sku: 'ACC-008', description: 'Cinturón de cuero genuino con hebilla metálica.', price: 39.99, originalPrice: null, currency: 'USD', stock: 4, category: 'Accesorios', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=ACC-008'], brand: 'CottonShop', sizes: ['S', 'M', 'L'], colors: ['Negro', 'Café'] },
  { id: 'p9', name: 'Pantalón Cargo Militar', sku: 'PAN-009', description: 'Pantalón cargo con múltiples bolsillos y corte militar.', price: 69.99, originalPrice: null, currency: 'USD', stock: 15, category: 'Pantalones', status: 'active', images: ['https://placehold.co/200x200/E2E8F0/475569?text=PAN-009'], brand: 'DenimCo', sizes: ['30', '32', '34'], colors: ['Verde Oliva', 'Negro'] },
  { id: 'p10', name: 'Chamarra Bomber Acolchada', sku: 'CHQ-010', description: 'Chamarra bomber con forro acolchado y cierre frontal.', price: 99.99, originalPrice: null, currency: 'USD', stock: 8, category: 'Chaquetas', status: 'draft', images: ['https://placehold.co/200x200/E2E8F0/475569?text=CHQ-010'], brand: 'UrbanStyle', sizes: ['S', 'M', 'L', 'XL'], colors: ['Verde Oliva', 'Negro'] },
];